### ISSUE TITLE
我这还得修炼多长时间啊

### ISSUE THREAD

**Issue by junareny** [yangyangwithgnu/the_new_world_linux#10]
我在github下载个项目运行起来都花了整整一天时间，有点气馁。到你这里我发现这网络都这么难的，别说整个互联网了

**Comment by tkizm1** [comment]
[proxychains-ng
](https://github.com/rofl0r/proxychains-ng)

proxychains4 git clone --depth 1 https://github.com/yangyangwithgnu/the_new_world_linux/
